### PR TITLE
sources/markdown: fix leading spaces in list items causing a panic

### LINKED ISSUE #121: Panic due to extra spaces
This works
```
## Unreleased

### Bugfix
- `imagePullPolicy` is now correctly applied to the init container as well.
```

The same with extra spaces causes a panic:
```
## Unreleased

### Bugfix
- `imagePullPolicy` is now correctly applied to the init container as well.    <--this are extra spaces
```

Trace 😱 
```
panic: node *ast.Hardbreak NYI

goroutine 1 [running]:
github.com/gomarkdown/markdown/md.(*Renderer).RenderNode(0x100f9c108?, {0x1009c4160?, 0x14000092690?}, {0x1009ca698?, 0x140003fc960?}, 0x60?)
        /Users/pgallina/go/pkg/mod/github.com/gomarkdown/markdown@v0.0.0-20220627144906-e9a81102ebeb/md/md_renderer.go:293 +0xa30
github.com/gomarkdown/markdown.Render.func1({0x1009ca698?, 0x140003fc960?}, 0xf8?)
        /Users/pgallina/go/pkg/mod/github.com/gomarkdown/markdown@v0.0.0-20220627144906-e9a81102ebeb/markdown.go:63 +0x50
github.com/gomarkdown/markdown/ast.NodeVisitorFunc.Visit(0x140005e4240?, {0x1009ca698?, 0x140003fc960?}, 0x58?)
        /Users/pgallina/go/pkg/mod/github.com/gomarkdown/markdown@v0.0.0-20220627144906-e9a81102ebeb/ast/node.go:563 +0x38
github.com/gomarkdown/markdown/ast.Walk({0x1009ca698, 0x140003fc960}, {0x1009c57c0, 0x14000076340})
        /Users/pgallina/go/pkg/mod/github.com/gomarkdown/markdown@v0.0.0-20220627144906-e9a81102ebeb/ast/node.go:535 +0x58
github.com/gomarkdown/markdown/ast.Walk({0x1009ca9b0, 0x140005e4240}, {0x1009c57c0, 0x14000076340})
        /Users/pgallina/go/pkg/mod/github.com/gomarkdown/markdown@v0.0.0-20220627144906-e9a81102ebeb/ast/node.go:546 +0x140
github.com/gomarkdown/markdown/ast.WalkFunc(...)
        /Users/pgallina/go/pkg/mod/github.com/gomarkdown/markdown@v0.0.0-20220627144906-e9a81102ebeb/ast/node.go:569
github.com/gomarkdown/markdown.Render({0x1009ca9b0, 0x140005e4240}, {0x1009c7ef8, 0x1400062c300})
        /Users/pgallina/go/pkg/mod/github.com/gomarkdown/markdown@v0.0.0-20220627144906-e9a81102ebeb/markdown.go:62 +0xd8
github.com/newrelic/release-toolkit/src/changelog/sources/markdown.items({0x140000761d0?, 0x1, 0x10080a576?})
        /Users/pgallina/go/pkg/mod/github.com/newrelic/release-toolkit@v0.0.0-20221019154739-6d5181fc033d/src/changelog/sources/markdown/md.go:164 +0x28c
github.com/newrelic/release-toolkit/src/changelog/sources/markdown.builder.entriesFromHeader({0x140003fdb80?, 0x140004683c0?, 0x140000925a0?}, 0x140003fdc20, {0x1007f0c4f, 0x6})
        /Users/pgallina/go/pkg/mod/github.com/newrelic/release-toolkit@v0.0.0-20221019154739-6d5181fc033d/src/changelog/sources/markdown/md.go:110 +0xec
github.com/newrelic/release-toolkit/src/changelog/sources/markdown.builder.build({0x140003fdb80, 0x0?, 0x0?})
        /Users/pgallina/go/pkg/mod/github.com/newrelic/release-toolkit@v0.0.0-20221019154739-6d5181fc033d/src/changelog/sources/markdown/md.go:82 +0x384
github.com/newrelic/release-toolkit/src/changelog/sources/markdown.Markdown.Changelog({{0x1009c50a0?, 0x14000554378?}})
        /Users/pgallina/go/pkg/mod/github.com/newrelic/release-toolkit@v0.0.0-20221019154739-6d5181fc033d/src/changelog/sources/markdown/md.go:50 +0x7c
github.com/newrelic/release-toolkit/src/app/generate.Generate(0x140001e4940)
        /Users/pgallina/go/pkg/mod/github.com/newrelic/release-toolkit@v0.0.0-20221019154739-6d5181fc033d/src/app/generate/generate.go:151 +0x46c
github.com/urfave/cli/v2.(*Command).Run(0x100cec900, 0x140001e4640)
        /Users/pgallina/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/command.go:173 +0x5ac
github.com/urfave/cli/v2.(*App).RunContext(0x140001a2540, {0x1009c8e10?, 0x140000280d0}, {0x14000020080, 0x8, 0x8})
        /Users/pgallina/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:383 +0xb90
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/pgallina/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:252
main.main()
        /Users/pgallina/go/pkg/mod/github.com/newrelic/release-toolkit@v0.0.0-20221019154739-6d5181fc033d/main.go:11 +0x48
exit status 2
make: *** [_release-changes-chart] Error 1

```

### PR DESCRIPTION
**Pull request by roobre**
Two or more leading spaces on a list item causes the markdown parser to include an `*ast.Hardbreak` node after the usual `*ast.Paragraph` one. This should not be a concern, but it turns out the markdown renderer is not able to render `*ast.Hardbreak`, and it panics when they are fed to it.

This PR works around that by introducing a `FilterRenderer`, which thinly wraps a `markdown.Renderer` but skips passing it nodes it does not support.

PR also comes with a test that will fail if this hack is no longer necessary.

Closes #121

### CODE REVIEW

File: src/changelog/sources/markdown/filter.go [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+
+// FilterRenderer wraps a markdown.Renderer skips calling it for certain node types.
+// This allows to use the default markdown renderer with types it does not support without it panicking.
+type FilterRenderer struct {
+	filtered map[reflect.Type]bool
+	markdown.Renderer
+}
+
+// NewFilterRenderer returns a FilterRenderer given an underlying renderer and a list of nodes whose type will be ignored.
+func NewFilterRenderer(inner markdown.Renderer, ignore ...interface{}) FilterRenderer {
```
Comment (sigilioso) [inline src/changelog/sources/markdown/filter.go:19]:
```suggestion
func NewFilterRenderer(inner markdown.Renderer, ignore ...ast.Node) FilterRenderer {
```

As it is supposed to be used with Node types, would it make sense to use the Node interface instead of any type?

File: src/changelog/sources/markdown/filter.go [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+}
+
+// RenderNode implements markdown.Renderer with the additional filtering logic.
+func (fr FilterRenderer) RenderNode(w io.Writer, node ast.Node, entering bool) ast.WalkStatus {
+	if fr.filtered[reflect.TypeOf(node)] {
+		return ast.GoToNext
+	}
+
+	return fr.Renderer.RenderNode(w, node, entering)
+}
```
Comment (sigilioso) [inline src/changelog/sources/markdown/filter.go:38]: Nit: I am aware this is already tested using the `md_test.go` but did you consider also adding a unit-test? (Even if it is a simple and potentially temporal wrapper)

**Review by sigilioso — APPROVED** [review]
LGTM 👍 

I left a couple of _nits_

File: src/changelog/sources/markdown/filter.go (hunk 1 above)
Comment (roobre) [reply src/changelog/sources/markdown/filter.go:19]: This is a nice idea, I like that.

File: src/changelog/sources/markdown/filter.go (hunk 2 above)
Comment (roobre) [reply src/changelog/sources/markdown/filter.go:38]: Added in https://github.com/newrelic/release-toolkit/pull/125/commits/7fb6b72db8ada112e715a6c681fc4e101f93c0ad

Comment (sigilioso) [reply src/changelog/sources/markdown/filter.go:38]: 👍

**Comment by sigilioso** [comment]
Thanks for taking care of it and addressing the comments 👍

**Comment by paologallinaharbur** [comment]
I wanted to check some black magic but I arrived late 😕
